name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-server: ${{ steps.image-name.outputs.IMAGE_SERVER }}
      image-name: ${{ steps.image-name.outputs.IMAGE_NAME }}
      image-version: ${{ steps.image-version.outputs.IMAGE_VERSION }}
    env:
      IMAGE_SERVER: rutzscolabcr.azurecr.io
      IMAGE_NAME: custom-chat-copilot/ingestion-functions
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t ingestion-functions .

      - name: Log in to ACR
        uses: docker/login-action@v1
        with:
          registry: rutzscolabcr.azurecr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Get the current date
        id: date
        run: echo "::set-output name=tag::$(date +'%Y%m%d%H%M%S')"
        
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_SERVER }}/${{ env.IMAGE_NAME }}:${{ steps.date.outputs.tag }}

      - name: Set image name for other jobs
        id: image-name
        run: |
          echo 'IMAGE_SERVER=${{ env.IMAGE_SERVER }}' >> $GITHUB_OUTPUT
          echo "IMAGE_NAME=${{ env.IMAGE_NAME }}" >> $GITHUB_OUTPUT
          
      - name: Set image version for other jobs
        id: image-version
        run: echo "IMAGE_VERSION=${{ steps.date.outputs.tag }}" >> $GITHUB_OUTPUT

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      IMAGE_SERVER: ${{ needs.build.outputs.image-server }}
      IMAGE_NAME: ${{ needs.build.outputs.image-name }}
      IMAGE_VERSION: ${{ needs.build.outputs.image-version }}
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ECHO VARIABLES
        run: |
          echo "IMAGE_SERVER = $IMAGE_SERVER"
          echo "IMAGE_NAME = $IMAGE_NAME"
          echo "IMAGE_VERSION = $IMAGE_VERSION"
        
      - name: Deploy to server       
        run: |
         az functionapp create --name ingestionservice --storage-account rutzscochatcopilotdfunsa --environment rutzsco-chat-copilot-demo --resource-group rutzsco-chat-copilot-demo --functions-version 4 --runtime python --image "rutzscolabcr.azurecr.io/custom-chat-copilot/ingestion-functions:$IMAGE_VERSION"
